sign_ele = {'Aries': 'fire',
'Leo': 'fire', 
'Sagittarius': 'fire',
'Taurus': 'earth',
'Virgo': 'earth', 
'Capricorn': 'earth',
'Gemini': 'air',
'Libra': 'air', 
'Aquarius': 'air',
'Cancer': 'water',
'Scorpio': 'water', 
'Pisces': 'water'}
